### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by LebsterFace** [shiftos-archive/source-0-0-x#1]
@alkalinethunder 
Hi, I'm a complete noob at Visual Studio and I was wondering if you could build this project into an exe somehow as I do not know how to and would really like to try out this version of the game. Much appriciated, thanks!

**Comment by ghost** [comment]
Long story short: No, I can't.

I've long since moved onto .NET Core and Unreal Engine 4, I no longer have the development environment required to build ShiftOS.  I also don't get in the habit of compiling old code to send people binary copies.

The game's code is open-source and archived for historical purposes, for people to look at and learn from.  I can't remember if we host precompiled binaries here yet on another repository, but I'm sure I culd talk to Phil - the original developer - and source some of the releases he made.

**Comment by AshesOfEther** [comment]
Assuming you're on Windows, you should be able to just clone the repository (Or download it from the website if you don't have Git), `cd` to it in CMD and run `msbuild`. I'm not sure where the output is, but look for folders called something like `obj`, `build`, `Release` or `Debug`.
